//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UnionMesas
    {
        public int ID { get; set; }
        public Nullable<int> Id_Mesa { get; set; }
        public Nullable<int> Id_Relacion { get; set; }
    
        public virtual Tbl_Mesas Tbl_Mesas { get; set; }
        public virtual Tbl_Relacion Tbl_Relacion { get; set; }
    }
}
