//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Cuentas()
        {
            this.Tbl_Ordenes = new HashSet<Tbl_Ordenes>();
        }
    
        public int ID { get; set; }
        public int Numero_Personas { get; set; }
        public decimal Deducible_total { get; set; }
        public decimal Total { get; set; }
        public decimal Total_Neto { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Estado { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public Nullable<int> id_Mesa { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
    
        public virtual Tbl_Areas Tbl_Areas { get; set; }
        public virtual Tbl_Clientes Tbl_Clientes { get; set; }
        public virtual Tbl_Estado Tbl_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Ordenes> Tbl_Ordenes { get; set; }
    }
}
