//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Ordenes()
        {
            this.Tbl_DetalleOrden = new HashSet<Tbl_DetalleOrden>();
        }
    
        public int ID { get; set; }
        public int Id_Cuenta { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Deducible { get; set; }
        public System.DateTime Fecha_Entrega { get; set; }
        public System.TimeSpan Hora_Entrega { get; set; }
        public string Nombre_Orden { get; set; }
    
        public virtual Tbl_Cuentas Tbl_Cuentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DetalleOrden> Tbl_DetalleOrden { get; set; }
    }
}
