//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Productos()
        {
            this.Tbl_DetalleOrden = new HashSet<Tbl_DetalleOrden>();
        }
    
        public int ID { get; set; }
        public string NombreProducto { get; set; }
        public decimal Precio { get; set; }
        public int Id_TipoProducto { get; set; }
        public int Id_Categoria { get; set; }
        public Nullable<int> Id_AreaDeImpresion { get; set; }
    
        public virtual Tbl_AreaDeImpresion Tbl_AreaDeImpresion { get; set; }
        public virtual Tbl_Categorias Tbl_Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DetalleOrden> Tbl_DetalleOrden { get; set; }
        public virtual Tbl_TipoProductos Tbl_TipoProductos { get; set; }
    }
}
