//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MesasReservas
    {
        public int id { get; set; }
        public int Id_Mesa { get; set; }
        public bool Estado { get; set; }
        public string Nombre_Cliente { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Tbl_Mesas Tbl_Mesas { get; set; }
    }
}
