//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Mesas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Mesas()
        {
            this.Tbl_MesasReservas = new HashSet<Tbl_MesasReservas>();
            this.Tbl_UnionMesas = new HashSet<Tbl_UnionMesas>();
        }
    
        public int ID { get; set; }
        public string Nombre_Mesa { get; set; }
        public int Capacidad { get; set; }
        public int Id_Reservas { get; set; }
        public bool Estado { get; set; }
        public int Id_Area { get; set; }
        public bool EsHabitacion { get; set; }
        public int Id_UnionMesas { get; set; }
        public virtual Tbl_Areas Tbl_Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MesasReservas> Tbl_MesasReservas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UnionMesas> Tbl_UnionMesas { get; set; }
    }
}
