//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Usuarios
    {
        public int ID { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public int Id_Empleado { get; set; }
        public int Id_Rol { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Tbl_Empleados Tbl_Empleados { get; set; }
        public virtual Tbl_Roles Tbl_Roles { get; set; }
    }
}
