//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Transacciones
    {
        public int ID { get; set; }
        public int Id_Acciones { get; set; }
        public Nullable<int> Id_Orden { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public Nullable<int> Id_Cuenta { get; set; }
        public Nullable<decimal> Excedente { get; set; }
        public Nullable<decimal> deducible { get; set; }
        public Nullable<decimal> Total { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan hora { get; set; }
    
        public virtual Tbl_Acciones Tbl_Acciones { get; set; }
    }
}
